//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FINANCEIROAPOLICE
    {
        public int IDFINANAPOLICE { get; set; }
        public int IDAPOLICE { get; set; }
        public int NUMPARCELA { get; set; }
        public System.DateTime DTVENCIMENTO { get; set; }
        public decimal VALORPARCELA { get; set; }
        public Nullable<System.DateTime> DTPAGTO { get; set; }
        public Nullable<decimal> VALORPAGTO { get; set; }
        public Nullable<decimal> VALORCOMISSAO { get; set; }
        public Nullable<int> STATUS { get; set; }
    
        public virtual APOLICE APOLICE { get; set; }
    }
}
