//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VibeApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEGURADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SEGURADO()
        {
            this.APOLICE = new HashSet<APOLICE>();
        }
    
        public int IDSEGURADO { get; set; }
        public string NOMESEGURADO { get; set; }
        public System.DateTime DTNASC { get; set; }
        public string CPF { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APOLICE> APOLICE { get; set; }
    }
}
